// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: aggregator.proto

package aggregator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *Operator              `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_aggregator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type RegisterRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Respond       string                 `protobuf:"bytes,1,opt,name=respond,proto3" json:"respond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRespond) Reset() {
	*x = RegisterRespond{}
	mi := &file_aggregator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRespond) ProtoMessage() {}

func (x *RegisterRespond) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRespond.ProtoReflect.Descriptor instead.
func (*RegisterRespond) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRespond) GetRespond() string {
	if x != nil {
		return x.Respond
	}
	return ""
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_aggregator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type DeregisterRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Respond       string                 `protobuf:"bytes,1,opt,name=respond,proto3" json:"respond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRespond) Reset() {
	*x = DeregisterRespond{}
	mi := &file_aggregator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRespond) ProtoMessage() {}

func (x *DeregisterRespond) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRespond.ProtoReflect.Descriptor instead.
func (*DeregisterRespond) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterRespond) GetRespond() string {
	if x != nil {
		return x.Respond
	}
	return ""
}

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Stake         uint64                 `protobuf:"varint,2,opt,name=Stake,proto3" json:"Stake,omitempty"`
	Models        []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_aggregator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{4}
}

func (x *Operator) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Operator) GetStake() uint64 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *Operator) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_aggregator_proto protoreflect.FileDescriptor

const file_aggregator_proto_rawDesc = "" +
	"\n" +
	"\x10aggregator.proto\x12\x03avs\"<\n" +
	"\x0fRegisterRequest\x12)\n" +
	"\boperator\x18\x01 \x01(\v2\r.avs.OperatorR\boperator\"+\n" +
	"\x0fRegisterRespond\x12\x18\n" +
	"\arespond\x18\x01 \x01(\tR\arespond\"+\n" +
	"\x11DeregisterRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"-\n" +
	"\x11DeregisterRespond\x12\x18\n" +
	"\arespond\x18\x01 \x01(\tR\arespond\"P\n" +
	"\bOperator\x12\x16\n" +
	"\x06Pubkey\x18\x01 \x01(\tR\x06Pubkey\x12\x14\n" +
	"\x05Stake\x18\x02 \x01(\x04R\x05Stake\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models2\x97\x01\n" +
	"\x0fOperatorService\x12>\n" +
	"\x10RegisterOperator\x12\x14.avs.RegisterRequest\x1a\x14.avs.RegisterRespond\x12D\n" +
	"\x12DeregisterOperator\x12\x16.avs.DeregisterRequest\x1a\x16.avs.DeregisterRespondB\x12Z\x10proto/aggregatorb\x06proto3"

var (
	file_aggregator_proto_rawDescOnce sync.Once
	file_aggregator_proto_rawDescData []byte
)

func file_aggregator_proto_rawDescGZIP() []byte {
	file_aggregator_proto_rawDescOnce.Do(func() {
		file_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregator_proto_rawDesc), len(file_aggregator_proto_rawDesc)))
	})
	return file_aggregator_proto_rawDescData
}

var file_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aggregator_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: avs.RegisterRequest
	(*RegisterRespond)(nil),   // 1: avs.RegisterRespond
	(*DeregisterRequest)(nil), // 2: avs.DeregisterRequest
	(*DeregisterRespond)(nil), // 3: avs.DeregisterRespond
	(*Operator)(nil),          // 4: avs.Operator
}
var file_aggregator_proto_depIdxs = []int32{
	4, // 0: avs.RegisterRequest.operator:type_name -> avs.Operator
	0, // 1: avs.OperatorService.RegisterOperator:input_type -> avs.RegisterRequest
	2, // 2: avs.OperatorService.DeregisterOperator:input_type -> avs.DeregisterRequest
	1, // 3: avs.OperatorService.RegisterOperator:output_type -> avs.RegisterRespond
	3, // 4: avs.OperatorService.DeregisterOperator:output_type -> avs.DeregisterRespond
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aggregator_proto_init() }
func file_aggregator_proto_init() {
	if File_aggregator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregator_proto_rawDesc), len(file_aggregator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregator_proto_goTypes,
		DependencyIndexes: file_aggregator_proto_depIdxs,
		MessageInfos:      file_aggregator_proto_msgTypes,
	}.Build()
	File_aggregator_proto = out.File
	file_aggregator_proto_goTypes = nil
	file_aggregator_proto_depIdxs = nil
}
