// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: socket.proto

package socket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote int32

const (
	Vote_VOTE_UNSPECIFIED Vote = 0
	Vote_VOTE_YES         Vote = 1
	Vote_VOTE_NO          Vote = 2
)

// Enum value maps for Vote.
var (
	Vote_name = map[int32]string{
		0: "VOTE_UNSPECIFIED",
		1: "VOTE_YES",
		2: "VOTE_NO",
	}
	Vote_value = map[string]int32{
		"VOTE_UNSPECIFIED": 0,
		"VOTE_YES":         1,
		"VOTE_NO":          2,
	}
)

func (x Vote) Enum() *Vote {
	p := new(Vote)
	*p = x
	return p
}

func (x Vote) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vote) Descriptor() protoreflect.EnumDescriptor {
	return file_socket_proto_enumTypes[0].Descriptor()
}

func (Vote) Type() protoreflect.EnumType {
	return &file_socket_proto_enumTypes[0]
}

func (x Vote) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vote.Descriptor instead.
func (Vote) EnumDescriptor() ([]byte, []int) {
	return file_socket_proto_rawDescGZIP(), []int{0}
}

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddress   string                 `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	TaskId        uint64                 `protobuf:"varint,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_socket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_socket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_socket_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMessage) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *TaskMessage) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskMessage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TaskMessage) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type TaskResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Resps         []string               `protobuf:"bytes,3,rep,name=resps,proto3" json:"resps,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponseMessage) Reset() {
	*x = TaskResponseMessage{}
	mi := &file_socket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponseMessage) ProtoMessage() {}

func (x *TaskResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_socket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponseMessage.ProtoReflect.Descriptor instead.
func (*TaskResponseMessage) Descriptor() ([]byte, []int) {
	return file_socket_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponseMessage) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResponseMessage) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *TaskResponseMessage) GetResps() []string {
	if x != nil {
		return x.Resps
	}
	return nil
}

func (x *TaskResponseMessage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ResponseVoteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *TaskResponseMessage   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Vote          Vote                   `protobuf:"varint,3,opt,name=vote,proto3,enum=avs.Vote" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseVoteMessage) Reset() {
	*x = ResponseVoteMessage{}
	mi := &file_socket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseVoteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVoteMessage) ProtoMessage() {}

func (x *ResponseVoteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_socket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVoteMessage.ProtoReflect.Descriptor instead.
func (*ResponseVoteMessage) Descriptor() ([]byte, []int) {
	return file_socket_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseVoteMessage) GetResponse() *TaskResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseVoteMessage) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *ResponseVoteMessage) GetVote() Vote {
	if x != nil {
		return x.Vote
	}
	return Vote_VOTE_UNSPECIFIED
}

var File_socket_proto protoreflect.FileDescriptor

const file_socket_proto_rawDesc = "" +
	"\n" +
	"\fsocket.proto\x12\x03avs\"w\n" +
	"\vTaskMessage\x12!\n" +
	"\fnode_address\x18\x01 \x01(\tR\vnodeAddress\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\x04R\x06taskId\"}\n" +
	"\x13TaskResponseMessage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\x12\x14\n" +
	"\x05resps\x18\x03 \x03(\tR\x05resps\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"\x8d\x01\n" +
	"\x13ResponseVoteMessage\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.avs.TaskResponseMessageR\bresponse\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\x12\x1d\n" +
	"\x04vote\x18\x03 \x01(\x0e2\t.avs.VoteR\x04vote*7\n" +
	"\x04Vote\x12\x14\n" +
	"\x10VOTE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bVOTE_YES\x10\x01\x12\v\n" +
	"\aVOTE_NO\x10\x022\x91\x01\n" +
	"\vTaskService\x12<\n" +
	"\n" +
	"TaskStream\x12\x18.avs.TaskResponseMessage\x1a\x10.avs.TaskMessage(\x010\x01\x12D\n" +
	"\n" +
	"VoteStream\x12\x18.avs.ResponseVoteMessage\x1a\x18.avs.TaskResponseMessage(\x010\x01B\x0eZ\fproto/socketb\x06proto3"

var (
	file_socket_proto_rawDescOnce sync.Once
	file_socket_proto_rawDescData []byte
)

func file_socket_proto_rawDescGZIP() []byte {
	file_socket_proto_rawDescOnce.Do(func() {
		file_socket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_socket_proto_rawDesc), len(file_socket_proto_rawDesc)))
	})
	return file_socket_proto_rawDescData
}

var file_socket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_socket_proto_goTypes = []any{
	(Vote)(0),                   // 0: avs.Vote
	(*TaskMessage)(nil),         // 1: avs.TaskMessage
	(*TaskResponseMessage)(nil), // 2: avs.TaskResponseMessage
	(*ResponseVoteMessage)(nil), // 3: avs.ResponseVoteMessage
}
var file_socket_proto_depIdxs = []int32{
	2, // 0: avs.ResponseVoteMessage.response:type_name -> avs.TaskResponseMessage
	0, // 1: avs.ResponseVoteMessage.vote:type_name -> avs.Vote
	2, // 2: avs.TaskService.TaskStream:input_type -> avs.TaskResponseMessage
	3, // 3: avs.TaskService.VoteStream:input_type -> avs.ResponseVoteMessage
	1, // 4: avs.TaskService.TaskStream:output_type -> avs.TaskMessage
	2, // 5: avs.TaskService.VoteStream:output_type -> avs.TaskResponseMessage
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_socket_proto_init() }
func file_socket_proto_init() {
	if File_socket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_proto_rawDesc), len(file_socket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_socket_proto_goTypes,
		DependencyIndexes: file_socket_proto_depIdxs,
		EnumInfos:         file_socket_proto_enumTypes,
		MessageInfos:      file_socket_proto_msgTypes,
	}.Build()
	File_socket_proto = out.File
	file_socket_proto_goTypes = nil
	file_socket_proto_depIdxs = nil
}
