// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: socket.proto

package socket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_TaskStream_FullMethodName = "/avs.TaskService/TaskStream"
	TaskService_VoteStream_FullMethodName = "/avs.TaskService/VoteStream"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	TaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskResponseMessage, TaskMessage], error)
	VoteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResponseVoteMessage, TaskResponseMessage], error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) TaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskResponseMessage, TaskMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[0], TaskService_TaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskResponseMessage, TaskMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_TaskStreamClient = grpc.BidiStreamingClient[TaskResponseMessage, TaskMessage]

func (c *taskServiceClient) VoteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResponseVoteMessage, TaskResponseMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[1], TaskService_VoteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResponseVoteMessage, TaskResponseMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_VoteStreamClient = grpc.BidiStreamingClient[ResponseVoteMessage, TaskResponseMessage]

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	TaskStream(grpc.BidiStreamingServer[TaskResponseMessage, TaskMessage]) error
	VoteStream(grpc.BidiStreamingServer[ResponseVoteMessage, TaskResponseMessage]) error
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) TaskStream(grpc.BidiStreamingServer[TaskResponseMessage, TaskMessage]) error {
	return status.Errorf(codes.Unimplemented, "method TaskStream not implemented")
}
func (UnimplementedTaskServiceServer) VoteStream(grpc.BidiStreamingServer[ResponseVoteMessage, TaskResponseMessage]) error {
	return status.Errorf(codes.Unimplemented, "method VoteStream not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_TaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).TaskStream(&grpc.GenericServerStream[TaskResponseMessage, TaskMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_TaskStreamServer = grpc.BidiStreamingServer[TaskResponseMessage, TaskMessage]

func _TaskService_VoteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).VoteStream(&grpc.GenericServerStream[ResponseVoteMessage, TaskResponseMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskService_VoteStreamServer = grpc.BidiStreamingServer[ResponseVoteMessage, TaskResponseMessage]

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avs.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TaskStream",
			Handler:       _TaskService_TaskStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "VoteStream",
			Handler:       _TaskService_VoteStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "socket.proto",
}
